--DROP TABLE [SalesLT].[RefData]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SalesLT].[RefData](
	[REF_ID] [int] IDENTITY(1,1) NOT NULL,
	[DEST_TABLE_NAME] [nvarchar](20) NOT NULL,
	[REF_DATA_CLASS] [nvarchar](20) NOT NULL,
	[REF_DATA_CLASS_KEY] [nvarchar](100) NOT NULL,
	[REF_DATA_CLASS_VALUE] [nvarchar](255) NOT NULL,
	[DATE_ADDED] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [SalesLT].[RefData] ADD  CONSTRAINT [PK_RefData_REF_ID] PRIMARY KEY CLUSTERED 
(
	[REF_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [SalesLT].[RefData] ADD  CONSTRAINT [DF_RefData_DATE_ADDED]  DEFAULT (getdate()) FOR [DATE_ADDED]
GO

DROP TABLE [SalesLT].[MappingSheet];
CREATE TABLE [SalesLT].[MappingSheet](
	[SOURCE_ENTITY] [nvarchar](50) NOT NULL,
	[SOURCE_COL_NAME] [nvarchar](50) NOT NULL,
	[GENERIC_COL_NAME] [nvarchar](50) NOT NULL,
	[TARGET_ENTITY] [nvarchar](50) NOT NULL,
	[TARGET_COL_NAME] [nvarchar](50) NOT NULL,
	[REQUIRED_FLAG] [nvarchar](1) NOT NULL,
	[DEFAULT_VALUE_IF_OPTIONAL] [nvarchar](255) NOT NULL,
	[INGESTION_RULE] [nvarchar](50) NOT NULL,
	[DATE_ADDED] [datetime] NOT NULL DEFAULT CURRENT_TIMESTAMP);
