insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','LOC','inField001','LOC','LOC','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','DESCR','inField002','LOC','DESCR','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','OHPOST','inField003','LOC','OHPOST','Y','DATE-MM-SL-DD-SL-YYYY');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','FRZSTART','inField004','LOC','FRZSTART','Y','DATE-MM-SL-DD-SL-YYYY');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','SOURCECAL','inField005','LOC','SOURCECAL','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','DESTCAL','inField006','LOC','DESTCAL','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','TYPE','inField007','LOC','TYPE','Y','DECIMAL');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','ALTPLANTID','inField008','LOC','ALTPLANTID','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','CUST','inField009','LOC','CUST','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','TRANSZONE','inField010','LOC','TRANSZONE','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','LAT','inField011','LOC','LAT','Y','DECIMAL');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','LON','inField012','LOC','LON','Y','DECIMAL');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','ENABLESW','inField013','LOC','ENABLESW','Y','DECIMAL');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','FF_TRIGGER_CONTROL','inField014','LOC','FF_TRIGGER_CONTROL','Y','DECIMAL');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','LOC_TYPE','inField015','LOC','LOC_TYPE','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','VENDID','inField016','LOC','VENDID','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','COMPANYID','inField017','LOC','COMPANYID','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','WORKINGCAL','inField018','LOC','WORKINGCAL','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','SEQINTEXPORTDUR','inField019','LOC','SEQINTEXPORTDUR','N','DECIMAL');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','SEQINTIMPORTDUR','inField020','LOC','SEQINTIMPORTDUR','N','DECIMAL');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','SEQINTLASTEXPORTEDTOSEQ','inField021','LOC','SEQINTLASTEXPORTEDTOSEQ','N','DATE-MM-SL-DD-SL-YYYY');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','SEQINTLASTIMPORTEDFROMSEQ','inField022','LOC','SEQINTLASTIMPORTEDFROMSEQ','N','DATE-MM-SL-DD-SL-YYYY');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','POSTALCODE','inField023','LOC','POSTALCODE','N','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','COUNTRY','inField024','LOC','COUNTRY','N','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','CURRENCY','inField025','LOC','CURRENCY','N','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','WDDAREA','inField026','LOC','WDDAREA','N','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','BORROWINGPCT','inField027','LOC','BORROWINGPCT','N','DECIMAL');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','HIERARCHYLEVEL','inField028','LOC','HIERARCHYLEVEL','N','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','ORDERCOST','inField029','LOC','ORDERCOST','N','DECIMAL');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','SOURCELOC','inField030','LOC','SOURCELOC','N','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','U_NATIONLOCATIONID','inField031','LOC','U_NATIONLOCATIONID','N','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','U_PROFILE_DESIGNATION','inField032','LOC','U_PROFILE_DESIGNATION','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','U_ETHNICITY','inField033','LOC','U_ETHNICITY','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','U_CORP_VOLUME_GROUP','inField034','LOC','U_CORP_VOLUME_GROUP','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','U_SCHOOL_START_WK','inField035','LOC','U_SCHOOL_START_WK','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','U_TOURIST_FLAG','inField036','LOC','U_TOURIST_FLAG','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','U_COLD_SUMMER','inField037','LOC','U_COLD_SUMMER','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','U_WARM_WEATHER','inField038','LOC','U_WARM_WEATHER','Y','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','U_EXTREME_GROWTH','inField039','LOC','U_EXTREME_GROWTH','N','NONE');
insert into SalesLt.MappingSheet (SOURCE_ENTITY, SOURCE_COL_NAME, GENERIC_COL_NAME, TARGET_ENTITY, TARGET_COL_NAME, REQUIRED_FLAG,INGESTION_RULE) 
values ('LOC','U_CER_STORE','inField040','LOC','U_CER_STORE','N','NONE');